"""Initial schema

Revision ID: aaa1e639686b
Revises: 
Create Date: 2026-02-28 13:05:52.363041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa1e639686b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('revenue_annual_millions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_margin_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_tolerance', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sla_weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('working_capital_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('customer_churn_sensitivity', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sla_target_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('air_freight_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reroute_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('buffer_stock_percent', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cost_multiplier_air', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_multiplier_reroute', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('holding_cost_per_unit_per_day', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disruptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('port_id', sa.UUID(), nullable=False),
    sa.Column('disruption_type', sa.String(length=50), nullable=False),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expected_delay_days', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('daily_demand', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criticality_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('on_hand_units', sa.Integer(), nullable=False),
    sa.Column('reserved_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=False),
    sa.Column('selected_strategy_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('revenue_preserved', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('mitigation_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sla_achieved', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sla_penalty_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_financial_impact', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('generated_email_supplier', sa.String(), nullable=True),
    sa.Column('generated_email_logistics', sa.String(), nullable=True),
    sa.Column('generated_executive_summary', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('port_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('original_arrival_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    op.drop_table('recommendations')
    op.drop_table('inventory')
    op.drop_table('skus')
    op.drop_table('disruptions')
    op.drop_table('strategies')
    op.drop_table('ports')
    op.drop_table('companies')
    # ### end Alembic commands ###
